version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: page_state_saver_db
    environment: # TODO: Move to env
      POSTGRES_DB: page_state_saver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./testdata/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d page_state_saver"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: page_state_saver_app
    environment: # TODO: Move to env
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/page_state_saver?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 
